export const resources = {
  services: {
    title: "Services",
    resource: "services",
    columns: [
      { key: "title", label: "Title" },
      { key: "slug", label: "Slug" },
      { key: "sortOrder", label: "Order" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "slug", label: "Slug", required: true },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "details", label: "Details", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: {
      title: "",
      slug: "",
      summary: "",
      details: "",
      sortOrder: 0,
      isActive: true,
    },
  },
  projects: {
    title: "Projects",
    resource: "projects",
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
      { key: "year", label: "Year" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "category", label: "Category", required: true },
      { name: "location", label: "Location", required: true },
      { name: "year", label: "Year", required: true },
      { name: "status", label: "Status", required: true, type: "select", options: ["Completed", "Ongoing", "Planned"] },
      { name: "image", label: "Image URL", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: {
      title: "",
      category: "",
      location: "",
      year: "",
      status: "Completed",
      image: "",
      description: "",
      sortOrder: 0,
      isActive: true,
    },
  },
  gallery: {
    title: "Gallery",
    resource: "gallery",
    columns: [
      { key: "caption", label: "Caption" },
      { key: "altText", label: "Alt text" },
    ],
    fields: [
      { name: "imageUrl", label: "Image URL", required: true },
      { name: "altText", label: "Alt text", required: true },
      { name: "caption", label: "Caption", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { imageUrl: "", altText: "", caption: "", sortOrder: 0, isActive: true },
    imageKey: "imageUrl",
  },
  testimonials: {
    title: "Testimonials",
    resource: "testimonials",
    columns: [
      { key: "name", label: "Name" },
      { key: "role", label: "Role" },
    ],
    fields: [
      { name: "quote", label: "Quote", type: "textarea", required: true },
      { name: "name", label: "Name", required: true },
      { name: "role", label: "Role", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { quote: "", name: "", role: "", sortOrder: 0, isActive: true },
  },
  values: {
    title: "Company Values",
    resource: "values",
    columns: [
      { key: "title", label: "Title" },
      { key: "text", label: "Text" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "text", label: "Text", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { title: "", text: "", sortOrder: 0, isActive: true },
  },
  milestones: {
    title: "Milestones / Stats",
    resource: "milestones",
    columns: [
      { key: "value", label: "Value" },
      { key: "label", label: "Label" },
    ],
    fields: [
      { name: "value", label: "Value", required: true },
      { name: "label", label: "Label", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { value: "", label: "", sortOrder: 0, isActive: true },
  },
  timeline: {
    title: "Timeline",
    resource: "timeline",
    columns: [
      { key: "year", label: "Year" },
      { key: "title", label: "Title" },
    ],
    fields: [
      { name: "year", label: "Year", required: true },
      { name: "title", label: "Title", required: true },
      { name: "text", label: "Text", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { year: "", title: "", text: "", sortOrder: 0, isActive: true },
  },
  "process-steps": {
    title: "Process Steps",
    resource: "process-steps",
    columns: [
      { key: "step", label: "Step" },
      { key: "title", label: "Title" },
    ],
    fields: [
      { name: "step", label: "Step code", required: true },
      { name: "title", label: "Title", required: true },
      { name: "text", label: "Text", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { step: "", title: "", text: "", sortOrder: 0, isActive: true },
  },
  careers: {
    title: "Careers",
    resource: "careers",
    columns: [
      { key: "title", label: "Title" },
      { key: "type", label: "Type" },
      { key: "location", label: "Location" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "type", label: "Job type", required: true },
      { name: "location", label: "Location", required: true },
      { name: "summary", label: "Summary", type: "textarea", required: true },
      { name: "sortOrder", label: "Sort order", type: "number" },
      { name: "isActive", label: "Active", type: "checkbox" },
    ],
    empty: { title: "", type: "Full-time", location: "", summary: "", sortOrder: 0, isActive: true },
  },
};
